package com.eu.habbo.habbohotel.wired;

public enum WiredConditionType {
    MATCH_SSHOT(0),
    FURNI_HAVE_HABBO(1),
    TRIGGER_ON_FURNI(2),
    TIME_MORE_THAN(3),
    TIME_LESS_THAN(4),
    USER_COUNT(5),
    ACTOR_IN_TEAM(6),
    FURNI_HAS_FURNI(7),
    STUFF_IS(8),
    ACTOR_IN_GROUP(10),
    ACTOR_WEARS_BADGE(11),
    ACTOR_WEARS_EFFECT(12),
    NOT_MATCH_SSHOT(13),
    NOT_FURNI_HAVE_HABBO(14),
    NOT_ACTOR_ON_FURNI(15),
    NOT_USER_COUNT(16),
    NOT_ACTOR_IN_TEAM(17),
    NOT_FURNI_HAVE_FURNI(18),
    NOT_STUFF_IS(19),
    NOT_ACTOR_IN_GROUP(21),
    NOT_ACTOR_WEARS_BADGE(22),
    NOT_ACTOR_WEARS_EFFECT(23),
    DATE_RANGE(24),
    ACTOR_HAS_HANDITEM(25),
    TRIGGERER_MATCHES(26),
    NOT_TRIGGERER_MATCHES(27),
    TIME_MATCHES(28),
    DATE_MATCHES(29),
    NOT_HAS_HANDITEM(30),
    TEAM_IS_WINNING(31),
    PERFORMING_ACTION(32),
    NOT_PERFORMING_ACTION(33),
    TEAM_HAS_SCORE(34),
    CLOCK_TIME_MATCHES(35),
    FURNI_HAS_ALTITUDE(36),
    USER_DIRECTION(37),
    INPUT_SOURCE_QUANTITY(38),
    CAN_PERFORM_MOVE(39),
    HAS_VARIABLE(40),
    NOT_HAS_VARIABLE(41),
    VARIABLE_VALUE(42),
    VARIABLE_AGE(43),
    USER_LEVEL(44),
    CHEST_HAS_ITEMS(45),
    CHEST_HAS_ITEM_TYPES(46),
    MOVEMENT_VALIDATION(26); // legacy alias kept for old plugin references

    public final int code;

    WiredConditionType(int code) {
        this.code = code;
    }
}
